language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install: "pip install pytest==2.6.2 pytest-cov python-coveralls pytest-pep8==1.0.6 -egit+https://github.com/sigmavirus24/betamax.git@acb3622#egg=betamax"

script: py.test xbox/ --pep8 -v --cov xbox --cov-report term-missing
after_success:
  - coveralls
