language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install: "pip install -r test-requirements.txt pytest-cov python-coveralls"

script: py.test xbox/ --pep8 -v --cov xbox --cov-report term-missing
after_success:
  - coveralls
