language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install: "pip install python-coveralls pytest-cov"

script: py.test xbox/tests/ -v --cov xbox --cov-report term-missing
after_success:
  - coveralls
