language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install: "pip install pytest==2.6.2 pytest-cov python-coveralls pytest-pep8==1.0.6 betamax==0.4.1"

script: py.test xbox/ --pep8 -v --cov xbox --cov-report term-missing
after_success:
  - coveralls
